# Generated by Django 5.1.4 on 2024-12-31 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empid', models.AutoField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=30, null=True)),
                ('desg', models.CharField(max_length=30, null=True)),
                ('salary', models.FloatField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profiles')),
            ],
        ),
    ]
